import express from 'express';
import cors from 'cors';
import axios from 'axios';
import fs from 'fs-extra';
import path from 'path';
import http from 'http';
import { Server as SocketIOServer } from 'socket.io';

const app = express();
const server = http.createServer(app);
const io = new SocketIOServer(server, { cors: { origin: '*' } });

app.use(cors());
app.use(express.json());

const sendStatus = (msg) => {
  io.emit('status', msg);
  console.log('[STATUS]', msg);
};

app.get('/', (req, res) => {
  res.send('Polyglot Push backend running.');
});

app.post('/api/translate', async (req, res) => {
  try {
    const { repoUrl, targetLocales } = req.body;
    sendStatus(`Starting translation for ${repoUrl}`);

    const repoName = repoUrl.split('/').pop().replace('.git', '');
    const repoPath = path.join('./repos', repoName);

    await fs.ensureDir(repoPath);
    sendStatus(`✅ Repository folder ready: ${repoPath}`);

    const readmePath = path.join(repoPath, 'README.md');
    await fs.writeFile(readmePath, '# Sample README\nThis is Polyglot Push test.');

    sendStatus('📘 Translating README into multiple languages...');
    for (const locale of targetLocales) {
      const newFile = path.join(repoPath, `README.${locale}.md`);
      const translatedHeader = `# 🌍 README (${locale.toUpperCase()})\n\nAuto-generated by Polyglot Push.\n\n`;
      await fs.writeFile(newFile, translatedHeader + (await fs.readFile(readmePath)));
      sendStatus(`✅ Created README.${locale}.md`);
    }

    res.json({ success: true });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Translation failed' });
  }
});

const PORT = 5000;
server.listen(PORT, () => console.log(`🚀 Server running on http://localhost:${PORT}`));
