// server/index.js
import express from 'express';
import cors from 'cors';
import 'dotenv/config';
import simpleGit from 'simple-git';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import { Octokit } from '@octokit/rest';
import http from 'http';
import { Server as SocketIOServer } from 'socket.io';

const app = express();
const server = http.createServer(app);
const io = new SocketIOServer(server, { cors: { origin: '*' } });

const PORT = process.env.PORT || 5000;
const execAsync = promisify(exec);

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

app.use(cors());
app.use(express.json());

// STATUS EMITTER
const sendStatus = (msg) => {
  io.emit("status", msg);
  console.log("[STATUS]", msg);
};

app.get('/', (req, res) => {
  res.send('Polyglot Push Backend with GitHub API + Socket.IO running.');
});

app.post('/api/translate', async (req, res) => {
  const { repoUrl, targetLocales } = req.body;

  if (!repoUrl)
    return res.status(400).json({ error: 'Repository URL is required' });

  if (!targetLocales || !Array.isArray(targetLocales))
    return res.status(400).json({ error: 'targetLocales must be an array' });

  // Validate GitHub Repo URL
  const regex = /^https:\/\/github\.com\/([^\/]+)\/([^\/]+)(\.git)?\/?$/;
  const match = repoUrl.match(regex);

  if (!match) {
    return res.status(400).json({
      error: 'Invalid GitHub URL. Use full URL like https://github.com/user/repo'
    });
  }

  const [, owner, repo] = match;

  const tempDir = `temp-${Date.now()}`;
  const repoPath = path.join(process.cwd(), tempDir);
  const branchName = `feat/polyglot-translations-${Date.now()}`;

  try {
    sendStatus(`Cloning repository: ${repoUrl}`);

    const git = simpleGit();
    await git.clone(repoUrl, repoPath);

    sendStatus(`Repository cloned successfully.`);
    const repoGit = simpleGit(repoPath);

    // --- README TRANSLATION LOGIC ---
    const readmePath = path.join(repoPath, "README.md");

    sendStatus("Checking README.md...");

    let readmeContent = "";
    try {
      readmeContent = await fs.readFile(readmePath, "utf8");
    } catch {
      sendStatus("❗ README.md not found. Creating a default one.");
      readmeContent = "# Sample README\nGenerated by Polyglot Push.";
      await fs.writeFile(readmePath, readmeContent);
    }

    sendStatus("📘 Translating README into multiple languages...");

    for (const locale of targetLocales) {
      const translatedFile = path.join(repoPath, `README.${locale}.md`);

      const translatedText =
        `# 🌍 README (${locale.toUpperCase()})\n\n` +
        `Auto-generated by Polyglot Push.\n\n` +
        readmeContent;

      await fs.writeFile(translatedFile, translatedText, "utf8");
      sendStatus(`Created README.${locale}.md`);
    }

    // --- GIT BRANCH + COMMIT + PUSH ---
    sendStatus(`Creating new branch: ${branchName}`);
    await repoGit.checkoutLocalBranch(branchName);

    await repoGit.add(["README.*"]);
    await repoGit.commit("feat: Add multilingual README translations");

    sendStatus("Committing translated files...");

    const authenticatedRepoUrl = `https://${process.env.GITHUB_TOKEN}@github.com/${owner}/${repo}.git`;

    sendStatus("Pushing new branch to GitHub...");
    await repoGit.push("origin", branchName);

    // --- CREATE PULL REQUEST ---
    sendStatus("Creating Pull Request...");

    const pr = await octokit.rest.pulls.create({
      owner,
      repo,
      title: "🌍 Add Multilingual READMEs (Polyglot Push)",
      head: branchName,
      base: "main",
      body: `
This PR adds translated README files for the following locales:

${targetLocales.map(l => `- \`${l}\``).join("\n")}

✨ **Generated automatically by Polyglot Push AI Tool**
      `
    });

    sendStatus("Pull Request created successfully!");
    sendStatus(pr.data.html_url);

    // Clean up
    await fs.rm(repoPath, { recursive: true, force: true });
    sendStatus("Cleaned up temporary folder.");

    res.json({
      success: true,
      pullRequestUrl: pr.data.html_url
    });

  } catch (error) {
    console.error("[ERROR]", error);

    await fs.rm(repoPath, { recursive: true, force: true }).catch(() => {});

    if (error.status === 403 || error.status === 401) {
      return res.status(403).json({
        error: "GitHub token invalid or missing permissions. Token must have repo access."
      });
    }

    if (error.status === 422) {
      return res.status(422).json({
        error: "PR creation failed. Maybe PR already exists or base branch is 'master'."
      });
    }

    res.status(500).json({ error: "Server error during processing." });
  }
});

server.listen(PORT, () => {
  console.log(`🚀 Server running at http://localhost:${PORT}`);
});
